### ISSUE TITLE
이미지 업로드 기능

### ISSUE THREAD

**Issue by riemannulus** [UmaSupporter/UmaSupporter.Carrot#2]
**기능 세줄 요약**
이미지를 `UmaSuppoter.Server`에 업로드
파일명을 그대로 살려서 업로드

## **지금은 이런데요 (As-Is)**
기능이 읍슴니다

## **이렇게 만들고 싶어요 (To-Be)**
`UmaSuppoter.Server` 에 POST 엔트리포인트를 하나 파 둘 예정
단일 업로드 / 벌크 업로드 둘 다 지원해야 됨
생각하고 있는 건 POST 엔트리포인트 하나에 순차적으로 하나씩 날리는 건데, 만약에 멀티파트가 필요하면 요청

## **참고하면 좋은 내용들 (Cham-Go)**
단순 이미지 업로드
[https://velog.io/@kyungjune/axios로-image-업로드하기](https://velog.io/@kyungjune/axios로-image-업로드하기)

**Comment by nabi-chan** [comment]
> 생각하고 있는 건 POST 엔트리포인트 하나에 순차적으로 하나씩 날리는 건데, 만약에 멀티파트가 필요하면 요청

요부분 보고 고민허고 있는건데, 이미지 `[1.png, 2.png, 3.png]` 가 있다면
POST /endpoint/1.png
POST /endpoint/2.png
POST /endpoint/3.png
이렇게 3번의 API REQ가 이루어져야 하나요?

**Comment by nabi-chan** [comment]
그것보다 Authorization 필드에 비밀번호가 그대로 올라가는게 신경쓰이네요 라고 말할려고 했는데 생각해보니까 일반 유저에게 공개가 안되어서 상관 없겠군요 :0
